FROM postgres:9.5
# Image takes the following vars, see https://hub.docker.com/_/mysql/
# POSTGRES_PASSWORD=beo8hkii
# POSTGRES_USER=postgres
# PGDATA=/var/lib/postgresql/data
# POSTGRES_DB=brainspell
# POSTGRES_INITDB_ARGS

# it will execute files with extensions .sh and .sql that are found in
# /docker-entrypoint-initdb.d. You can easily populate your database by
# mounting a SQL dump into that directory

# We'll run this like so:
# docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
# OR
# docker run -it --link some-postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'
